"""
Core constants for the Resume Customizer application.
"""

# Application constants
DEFAULT_PAGE_TITLE = "Resume Customizer - AI-Powered Resume Enhancement"
DEFAULT_PAGE_ICON = "📄"
DEFAULT_LAYOUT = "wide"

# File processing constants
MAX_FILE_SIZE_MB = 10
MAX_UPLOAD_FILES = 5
SUPPORTED_EXTENSIONS = [".docx", ".doc", ".pdf"]
DEFAULT_ENCODING = "utf-8"

# Processing constants
DEFAULT_PROCESSING_TIMEOUT = 300  # 5 minutes
MAX_CONCURRENT_PROCESSES = 5
DEFAULT_BATCH_SIZE = 3

# UI constants
MAX_DISPLAY_FILES = 20
DEFAULT_PROGRESS_STEPS = 5
TOAST_DURATION_MS = 3000

# Cache constants
DEFAULT_CACHE_EXPIRE_HOURS = 1
MAX_CACHE_ENTRIES = 1000

# Email constants
DEFAULT_EMAIL_TIMEOUT = 30
MAX_EMAIL_RETRIES = 3
EMAIL_RETRY_DELAY = 5

# Database constants
DEFAULT_CONNECTION_POOL_SIZE = 10
DATABASE_TIMEOUT = 30
MAX_QUERY_RETRIES = 3

# Security constants
SESSION_TIMEOUT_MINUTES = 60
MAX_LOGIN_ATTEMPTS = 5
PASSWORD_MIN_LENGTH = 8

# Feature flags
FEATURE_ASYNC_PROCESSING = "async_processing"
FEATURE_BULK_OPERATIONS = "bulk_operations"
FEATURE_EMAIL_INTEGRATION = "email_integration"
FEATURE_GOOGLE_DRIVE = "google_drive"
FEATURE_ADVANCED_ANALYTICS = "advanced_analytics"

# Export all constants
__all__ = [
    'DEFAULT_PAGE_TITLE', 'DEFAULT_PAGE_ICON', 'DEFAULT_LAYOUT',
    'MAX_FILE_SIZE_MB', 'MAX_UPLOAD_FILES', 'SUPPORTED_EXTENSIONS', 'DEFAULT_ENCODING',
    'DEFAULT_PROCESSING_TIMEOUT', 'MAX_CONCURRENT_PROCESSES', 'DEFAULT_BATCH_SIZE',
    'MAX_DISPLAY_FILES', 'DEFAULT_PROGRESS_STEPS', 'TOAST_DURATION_MS',
    'DEFAULT_CACHE_EXPIRE_HOURS', 'MAX_CACHE_ENTRIES',
    'DEFAULT_EMAIL_TIMEOUT', 'MAX_EMAIL_RETRIES', 'EMAIL_RETRY_DELAY',
    'DEFAULT_CONNECTION_POOL_SIZE', 'DATABASE_TIMEOUT', 'MAX_QUERY_RETRIES',
    'SESSION_TIMEOUT_MINUTES', 'MAX_LOGIN_ATTEMPTS', 'PASSWORD_MIN_LENGTH',
    'FEATURE_ASYNC_PROCESSING', 'FEATURE_BULK_OPERATIONS', 'FEATURE_EMAIL_INTEGRATION',
    'FEATURE_GOOGLE_DRIVE', 'FEATURE_ADVANCED_ANALYTICS'
]