[theme]
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
headless = true
address = "0.0.0.0"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(message)s"

[global]
developmentMode = false
showWarningOnDirectExecution = false